package PersonnelAPP;


/**
* PersonnelAPP/EnseignantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* jeudi 1 juin 2017 15 h 55 EDT
*/

abstract public class EnseignantHelper
{
  private static String  _id = "IDL:PersonnelAPP/Enseignant:1.0";

  public static void insert (org.omg.CORBA.Any a, PersonnelAPP.Enseignant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PersonnelAPP.Enseignant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = PersonnelAPP.PersonInfoHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "p",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "tel",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "post",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PersonnelAPP.EnseignantHelper.id (), "Enseignant", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PersonnelAPP.Enseignant read (org.omg.CORBA.portable.InputStream istream)
  {
    PersonnelAPP.Enseignant value = new PersonnelAPP.Enseignant ();
    value.p = PersonnelAPP.PersonInfoHelper.read (istream);
    value.tel = istream.read_ulonglong ();
    value.post = istream.read_ulonglong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PersonnelAPP.Enseignant value)
  {
    PersonnelAPP.PersonInfoHelper.write (ostream, value.p);
    ostream.write_ulonglong (value.tel);
    ostream.write_ulonglong (value.post);
  }

}
