package PersonnelAPP;


/**
* PersonnelAPP/Enseignant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* mardi 23 mai 2017 18 h 30 EDT
*/

public final class Enseignant implements org.omg.CORBA.portable.IDLEntity
{
  public PersonnelAPP.PersonInfo p = null;
  public int tel = (int)0;
  public int post = (int)0;

  public Enseignant ()
  {
  } // ctor

  public Enseignant (PersonnelAPP.PersonInfo _p, int _tel, int _post)
  {
    p = _p;
    tel = _tel;
    post = _post;
  } // ctor

} // class Enseignant
