package PersonnelAPP;


/**
* PersonnelAPP/Etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* mardi 23 mai 2017 13 h 17 EDT
*/

public final class Etudiant implements org.omg.CORBA.portable.IDLEntity
{
  public PersonnelAPP.PersonInfo p = null;
  public int matricul = (int)0;

  public Etudiant ()
  {
  } // ctor

  public Etudiant (PersonnelAPP.PersonInfo _p, int _matricul)
  {
    p = _p;
    matricul = _matricul;
  } // ctor

} // class Etudiant
