package PersonnelAPP;


/**
* PersonnelAPP/EtudiantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* jeudi 1 juin 2017 14 h 13 EDT
*/

abstract public class EtudiantHelper
{
  private static String  _id = "IDL:PersonnelAPP/Etudiant:1.0";

  public static void insert (org.omg.CORBA.Any a, PersonnelAPP.Etudiant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PersonnelAPP.Etudiant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = PersonnelAPP.PersonInfoHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "p",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "matricul",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PersonnelAPP.EtudiantHelper.id (), "Etudiant", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PersonnelAPP.Etudiant read (org.omg.CORBA.portable.InputStream istream)
  {
    PersonnelAPP.Etudiant value = new PersonnelAPP.Etudiant ();
    value.p = PersonnelAPP.PersonInfoHelper.read (istream);
    value.matricul = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PersonnelAPP.Etudiant value)
  {
    PersonnelAPP.PersonInfoHelper.write (ostream, value.p);
    ostream.write_string (value.matricul);
  }

}
