package PersonnelAPP;


/**
* PersonnelAPP/PersonnelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* vendredi 2 juin 2017 16 h 03 EDT
*/


//Service de l'App
public interface PersonnelOperations 
{
  boolean creerEnseignant (PersonnelAPP.Enseignant e);
  boolean creerEtudiant (PersonnelAPP.Etudiant e);
  PersonnelAPP.Enseignant chercherEnseignant (String nom, String prenom);
  PersonnelAPP.Etudiant chercherEtudiant (String nom, String prenom);
  PersonnelAPP.Enseignant[] chercherEnseignantByDomain (String domain);
  PersonnelAPP.Etudiant[] chercherEtudiantByDomain (String domain);
  PersonnelAPP.Enseignant[] AfficherEnseigants ();
  PersonnelAPP.Etudiant[] AfficherEtudiants ();
  void supprimerEtudiant (PersonnelAPP.Etudiant e);
  void supprimerEnseigant (PersonnelAPP.Enseignant e);
  void modifierEnseignant (PersonnelAPP.Enseignant e, PersonnelAPP.Enseignant newEnseigant);
  void modifierEtudiant (PersonnelAPP.Etudiant e, PersonnelAPP.Etudiant newEtudiant);
  void shutdown ();
} // interface PersonnelOperations
