package PersonnelAPP;


/**
* PersonnelAPP/PersonInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* vendredi 2 juin 2017 16 h 03 EDT
*/

public final class PersonInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public String prenom = null;
  public String mail = null;
  public String domain = null;

  public PersonInfo ()
  {
  } // ctor

  public PersonInfo (String _nom, String _prenom, String _mail, String _domain)
  {
    nom = _nom;
    prenom = _prenom;
    mail = _mail;
    domain = _domain;
  } // ctor

} // class PersonInfo
