package PersonnelAPP;

/**
* PersonnelAPP/PersonnelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* mardi 30 mai 2017 12 h 59 EDT
*/


//Service de l'App
public final class PersonnelHolder implements org.omg.CORBA.portable.Streamable
{
  public PersonnelAPP.Personnel value = null;

  public PersonnelHolder ()
  {
  }

  public PersonnelHolder (PersonnelAPP.Personnel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PersonnelAPP.PersonnelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PersonnelAPP.PersonnelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PersonnelAPP.PersonnelHelper.type ();
  }

}
