package PersonnelAPP;


/**
* PersonnelAPP/Personnel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* mercredi 31 mai 2017 12 h 52 EDT
*/


//Service de l'App
public interface Personnel extends PersonnelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Personnel
