package PersonnelAPP;


/**
* PersonnelAPP/Personnel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* vendredi 2 juin 2017 16 h 03 EDT
*/


//Service de l'App
public interface Personnel extends PersonnelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Personnel
