package PersonnelAPP;


/**
* PersonnelAPP/PersonInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* mercredi 31 mai 2017 12 h 52 EDT
*/

abstract public class PersonInfoHelper
{
  private static String  _id = "IDL:PersonnelAPP/PersonInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, PersonnelAPP.PersonInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PersonnelAPP.PersonInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "prenom",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "mail",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "domain",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (PersonnelAPP.PersonInfoHelper.id (), "PersonInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PersonnelAPP.PersonInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    PersonnelAPP.PersonInfo value = new PersonnelAPP.PersonInfo ();
    value.nom = istream.read_string ();
    value.prenom = istream.read_string ();
    value.mail = istream.read_string ();
    value.domain = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PersonnelAPP.PersonInfo value)
  {
    ostream.write_string (value.nom);
    ostream.write_string (value.prenom);
    ostream.write_string (value.mail);
    ostream.write_string (value.domain);
  }

}
