package PersonnelAPP;


/**
* PersonnelAPP/PersonnelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersonnelAPP.idl
* mardi 23 mai 2017 13 h 17 EDT
*/


//Service de l'App
public interface PersonnelOperations 
{
  void creePersonne (PersonnelAPP.PersonInfo p);

  //*
  void creerEnseignant (PersonnelAPP.Enseignant e);
  void creerEtudiant (PersonnelAPP.Etudiant e);
  PersonnelAPP.Enseignant chercherEnseignant (String nom);
  PersonnelAPP.Etudiant chercherEtudiant (String nom);
  PersonnelAPP.Enseignant[] AfficherEnseigants ();
  PersonnelAPP.Etudiant[] AfficherEtudiants ();
  void supprimerEtudiant (PersonnelAPP.Etudiant e);
  void supprimerEnseigant (PersonnelAPP.Enseignant e);
  void modifierEnserignant (PersonnelAPP.Enseignant e, PersonnelAPP.Enseignant newEnseigant);
  void modifierEtudiant (PersonnelAPP.Etudiant e, PersonnelAPP.Etudiant newEtudiant);

  //*/
  void shutdown ();
} // interface PersonnelOperations
